#! /usr/bin/env python2

# converts a flash cookie (sol) to plain text (python repr)
# requires pyamf

# expects input from stdin
# writes to stdout
# no arguments

import ast
import pprint
import sys

import pyamf
from pyamf import sol

def main():
  filecontent = sys.stdin.read()
  try:
    pytuple = sol.decode(filecontent)
    pprint.pprint(pytuple)
  except pyamf.DecodeError:
    try:
      _string, _dict = ast.literal_eval(
            filecontent.replace('pyamf.Undefined', repr('pyamf.Undefined')))
      for key in _dict:
        if _dict[key] == 'pyamf.Undefined':
          _dict[key] = pyamf.Undefined
      solobject = sol.encode(_string, _dict)
      sys.stdout.write(solobject.getvalue())
    except SyntaxError:
      print 'error: cannot decode nor encode'

if __name__ == "__main__":
  main()
